version: 0.2

phases:
  #install:
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - pip install --quiet --upgrade --requirement requirements.txt
      - make lint unittest
      - make upload
      - make deploy ENV=staging
      - make test ENV=staging
      - make deploy ENV=production
      - make test ENV=production

#cache:
  #paths:
    # - paths
