version: 0.2

phases:
  #install:
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - pip install --quiet --upgrade --requirement requirements.txt
      - make lint unittest
      - ./upload-new-version.sh
      - ./deploy-new-version.sh staging
      - ./test-environment.sh staging
      - ./deploy-new-version.sh production
      - ./test-environment.sh production

#cache:
  #paths:
    # - paths
