version: 0.2

phases:
  #install:
    #commands:
      # - command
      # - command
  #pre_build:
    #commands:
      # - command
      # - command
  build:
    commands:
      - pip install --quiet --upgrade --requirement requirements.txt
      - make lint unittest
        #- bash ./upload-new-version.sh
        #- bash ./deploy-new-version.sh staging
        #- bash ./test-environment.sh staging
        #- bash ./deploy-new-version.sh production
        #- bash ./test-environment.sh production

#cache:
  #paths:
    # - paths
